version: 1.0.{build}
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: SEChBcrcncyPpcBR16gHZgXndto32LUGPhpC69rNSr8cw+2Yag+FblolQCuigsYDg7thvemFN8xu7mYXRevNUhAU7hsOp/OxupKiafCssgg=
  on:
    branch: master
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true